### ISSUE TITLE
Part 3: Security.java,  line 57

### ISSUE THREAD

**Issue by gracesaeri** [CSumm/assignment4#14]
String authInfo = authParts[0]; 
->
 String authInfo = authParts[1];

**Comment by gdstewart** [comment]
Olivier, Grace mentioned you said it did not work with index 1. I think the format for submitting Authorization headers is supposed to "Type + authstring" so in our case "Basic + Base64 encoded string", in which case the authstring will be in the index 1 position of the array. I hope this makes sense.

**Comment by SekoduNord** [comment]
Should work. Need to be tested.
