### ISSUE TITLE
Part 1 does not run.

### ISSUE THREAD

**Issue by gracesaeri** [CSumm/assignment4#2]
Clean + Build is fine;
when running the application, nothing happens.

**Comment by CSumm** [comment]
I think I figured out the issue. You're using saaj Base64 instead of Java utils. It should go into bytes and then convert the bytes into a String

**Comment by CSumm** [comment]
I can confirm the bug. Right clicking and running the Book Service class, no output is shown in the console, or no code bootup occurs.

**Comment by CSumm** [comment]
I've solved the issue of getting output console by following this post on StackOverflow:
https://stackoverflow.com/questions/46180366/netbeans-8-2-wont-run-the-project
Opened follow-up issue #8 .
